// src/App.tsx
// components
import { Hero } from './components/Hero/Hero'
// import { Wip } from './components/WIP/Wip'
import { HeaderNav } from './components/Header/HeaderNav'
import { AboutMe } from './components/AboutMe/AboutMe'
import { Projects } from './components/Projects/Projects'
import { Contact } from './components/Contact/Contact'
import { Footer } from './components/Footer/Footer'

// assets
import { ThemeProvider } from 'styled-components'
import { defaultTheme } from './themes/default'
import { GlobalStyles } from './GlobalStyles'

function App() {
  return (
    <ThemeProvider theme={defaultTheme}>
      <HeaderNav />
      <Hero />
      <AboutMe />
      <Projects />
      <Contact />
      <Footer />
      {/* <Wip /> */}
      <GlobalStyles />
    </ThemeProvider>
  )
}

export default App

// src/App.vue
<template>
  <Header />
  <Hero />
  <SocialMedia />
  <About />
  <Projects />
  <Contact />
</template>

<script>
// components
import Header from "./components/Header.vue";
import Hero from "./components/Hero.vue";
import SocialMedia from "./components/SocialMedia.vue";
import About from "./components/About.vue";
import Projects from "./components/Projects.vue";
import Contact from "./components/Contact.vue";

export default {
  name: "App",
  components: {
    Header,
    Hero,
    SocialMedia,
    About,
    Projects,
    Contact,
  },
};
</script>
